config/routes.rb
Rails.application.routes.draw do  
  namespace :admins do
    get 'toppages/index'
  end
  devise_for :admins, controllers: {
    sessions:      'admins/sessions',
    passwords:     'admins/passwords',
    #registrations: 'admins/registrations'
  }
  devise_scope :admin do
    get '/admins/sign_out' => 'admins/sessions#destroy'
  end
  devise_for :users, controllers: {
    sessions:      'users/sessions',
    passwords:     'users/passwords',
    registrations: 'users/registrations'
  }
  root to:"novels#index"
  get 'novels/complete'
  get 'novels/concept'
  resources :novels, only: [:index, :new, :create, :show, :edit, :update] do
    collection do
      get 'search'
      get 'search_area'
    end
  end
  resources :areas, only: [:new, :create, :show] do
    collection do
      get 'search'
    end
  end
end

app/views/shared/_footer.html.erb
<footer>

<div id="footermenu" class="inner">
	<ul>
		<li class="title">サイトメニュー</li>
		<li><%= link_to root_path do %>ホーム<% end %></li>
		<li><%= link_to novels_concept_path do %>コンセプト<% end %></li>
		<li><%= link_to new_novel_path do %>小説情報投稿<% end %></li>
		<li><a href="#">検索</a></li>
		<li><a href="#">お問い合わせ</a></li>
		<li><%= link_to new_admin_session_path do %>管理者ページ<% end %></li>
	</ul>
</div>
<!--/footermenu-->

<div id="copyright">
<span class="pr"><a href="https://template-party.com/" target="_blank">《Web Design:Template-Party》</a></span>
</div>

</footer>

<p class="nav-fix-pos-pagetop"><a href="#">↑</a></p>


</script>

<!--パララックス用ファイル読み込み-->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/protonet-jquery.inview/1.1.2/jquery.inview.min.js"></script>
<script src="js/jquery.inview_set.js"></script>

app/views/shared/_header.html.erb
<header>
  <div class="inner">
    <h1 id="logo"><%= image_tag "NOVEREA.gif" %></h1>
        
    <ul id="header-nav">
    <% if user_signed_in? %>
      <li><%= link_to "#" do %><%= current_user.nickname %>さんのマイページ<% end %></li>
      <li><%= link_to destroy_user_session_path, method: :delete do %>ログアウト<% end %></li>
    <% else %>
      <li><%= link_to new_user_session_path do %>ログイン<% end %></li>
      <li><%= link_to new_user_registration_path do %>新規登録<% end %></li>
    <% end %>
    </ul>
  </div>
</header>

<!--PC用（901px以上端末）メニュー-->
<nav id="menubar" class="nav-fix-pos">
  <ul class="inner">
    <li class="info"><%= link_to novels_path do %>ホーム<span>Home</span><% end %></li>
    <li class="event"><%= link_to novels_concept_path do %>コンセプト<span>Concept</span><% end %></li>
    <li class="shopping"><%= link_to new_novel_path do %>小説情報投稿<span>Post</span><% end %></li>
    <li class="shopping"><%= link_to '#' do %>検索<span>Search</span><% end %></li>
    <li class="contact"><%= link_to '#' do %>お問い合せ<span>Contact</span><% end %></li>
  </ul>
</nav>
<!--小さな端末用（900px以下端末）メニュー-->
<nav id="menubar-s">
  <ul>
    <li class="info"><%= link_to novels_path do %>ホーム<span>Home</span><% end %></li>
    <li class="event"><%= link_to novels_concept_path do %>コンセプト<span>Concept</span><% end %></li>
    <li class="shopping"><%= link_to new_novel_path do %>小説情報投稿<span>Post</span><% end %></li>
    <li class="shopping"><%= link_to '#' do %>検索<span>Search</span><% end %></li>
    <li class="contact"><%= link_to '#' do %>お問い合せ<span>Contact</span><% end %></li>
  </ul>
</nav>

app/views/shared/_shortheader.html.erb
<!--PC用（901px以上端末）メニュー-->
<nav id="menubar" class="nav-fix-pos">
  <ul class="inner">
    <li class="info"><%= link_to novels_path do %>ホーム<span>Home</span><% end %></li>
    <li class="event"><%= link_to novels_concept_path do %>コンセプト<span>Concept</span><% end %></li>
    <li class="shopping"><%= link_to new_novel_path do %>小説情報投稿<span>Post</span><% end %></li>
    <li class="shopping"><%= link_to '#' do %>検索<span>Search</span><% end %></li>
    <li class="contact"><%= link_to '#' do %>お問い合せ<span>Contact</span><% end %></li>
  </ul>
</nav>
<!--小さな端末用（900px以下端末）メニュー-->
<nav id="menubar-s">
  <ul>
    <li class="info"><%= link_to novels_path do %>ホーム<span>Home</span><% end %></li>
    <li class="event"><%= link_to novels_concept_path do %>コンセプト<span>Concept</span><% end %></li>
    <li class="shopping"><%= link_to new_novel_path do %>小説情報投稿<span>Post</span><% end %></li>
    <li class="shopping"><%= link_to '#' do %>検索<span>Search</span><% end %></li>
    <li class="contact"><%= link_to '#' do %>お問い合せ<span>Contact</span><% end %></li>
  </ul>
</nav>

app/views/shared/_simplesearch.html.erb
<h3>作品名・著者名から検索</h3>
<%= form_with(url: search_novels_path, local: true, method: :get) do |form| %>
  <%= form.text_field :keyword, placeholder: "作品タイトル・作者名から検索する",class:"simplesearch-novel" %>
  <%= form.submit "検索" , class:"simple-searchbtn" %>
<% end %><br>
<h3>地域名から検索</h3>
<%= search_form_for @q, url: search_areas_path do |f| %>
    <a class="simplesearch-area"><%= f.label :country_cont, '国名' %></a>
    <%= f.text_field :country_cont, placeholder: '国名',class:"simplesearch-areatext" %>
    <a class="simplesearch-area"><%= f.label :prefecture_cont, '都道府県/州' %></a>
    <%= f.text_field :prefecture_cont, placeholder: '都道府県/州',class:"simplesearch-areatext" %>
    <a class="simplesearch-area"> <%= f.label :city_cont, '市区町村' %></a>
    <%= f.text_field :city_cont, placeholder: '市区町村',class:"simplesearch-areatext" %>
<%= f.submit '検索', class:"simple-searchbtn" %>
<% end %>