config/routes.rb
Rails.application.routes.draw do  
  namespace :admins do
    get 'toppages/index'
  end
  devise_for :admins, controllers: {
    sessions:      'admins/sessions',
    passwords:     'admins/passwords',
    #registrations: 'admins/registrations'
  }
  devise_scope :admin do
    get '/admins/sign_out' => 'admins/sessions#destroy'
  end
  devise_for :users, controllers: {
    sessions:      'users/sessions',
    passwords:     'users/passwords',
    registrations: 'users/registrations'
  }
  root to:"novels#index"
  get 'novels/complete'
  get 'novels/concept'
  resources :novels, only: [:index, :new, :create, :show, :edit, :update] do
    collection do
      get 'search'
      get 'search_area'
    end
  end
  resources :areas, only: [:new, :create, :show] do
    collection do
      get 'search'
    end
  end
end

app/models/novel.rb
class Novel < ApplicationRecord
  has_many :novel_areas
  has_many :areas, through: :novel_areas

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :genre

  validates :title, presence: true
  validates :auther, presence: true

  def self.search(search)
    if search != ""
      Novel.where('title LIKE(?) OR auther LIKE(?) OR another_area LIKE(?) OR spot LIKE(?) ', "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%")
    else
      Novel.all
    end
  end
end

app/controllers/novels_controller.rb
class NovelsController < ApplicationController
  before_action :set_novel, only:[:show, :edit, :update]
  before_action :authenticate_user!, only:[:create, :edit, :update]

  def index
    @novels = Novel.includes(:areas).order("updated_at DESC")
    @novels = Kaminari.paginate_array(@novels).page(params[:page])
    
    @result = []

    @novels.each do |novel|
      title = novel.title
      auther = novel.auther
      search_rakuten_api(title, auther)
      @result << @item
    end
  end

  def new
    @novel = Novel.new
  end

  def create
    @novel = Novel.new(novel_params)
    if @novel.save
      redirect_to action: :complete
    else
      render :new
    end
  end
  
  def complete
  end

  def concept
  end

  def show
    title = @novel.title
    auther = @novel.auther
    search_rakuten_api(title, auther)
    search_rakuten_api_dvd(title)
  end

  def edit
  end

  def update
    if @novel.update(novel_params)
      redirect_to novel_path(@novel.id)
    else
      render :edit
    end
  end

  def search
    @novels = Novel.search(params[:keyword]).order("updated_at DESC")
    @novels = Kaminari.paginate_array(@novels).page(params[:page])

    @result = []

    @novels.each do |novel|
      title = novel.title
      auther = novel.auther
      search_rakuten_api(title, auther)
      @result << @item
    end
  end
  
  private
  def novel_params
    params.require(:novel).permit(:title, :auther, :release_year, :genre_id, :another_area, :spot, :synopsis, :mediamix, area_ids:[])
  end

  def set_novel
    @novel = Novel.find(params[:id])
  end

  def search_rakuten_api(title, auther)
    RakutenWebService.configure do |c|
      c.application_id = ENV["RAKUTEN_APP_KEY_ID"]
      c.affiliate_id = ENV["RAKUTEN_AFFILIATE_KEY_ID"]
    end
    items = RakutenWebService::Books::Book.search(title: title, auther: auther)
    items.first(1).each do |item|
      @item = item
    end
  end

  def search_rakuten_api_dvd(title)
    RakutenWebService.configure do |c|
      c.application_id = ENV["RAKUTEN_APP_KEY_ID"]
      c.affiliate_id = ENV["RAKUTEN_AFFILIATE_KEY_ID"]
    end
    items = RakutenWebService::Books::DVD.search(title: title)
    items.first(1).each do |item|
      @dvditem = item
    end
  end
end

app/helpers/novels_helper.rb
module NovelsHelper
end

app/views/novels/complete.html.erb
<body class="home">
<%= render "shared/header" %>
<div class="contents">
<div class="inner">

<section>
 <h2 class="simple">投稿が完了しました</h2>
  <p>
    <strong class="color1">
    <%= link_to 'さらに小説情報を投稿する', new_novel_path %><br>
    <%= link_to 'ホームに戻る', novels_path %></strong>
  </p>


</section>
</div>
<!--/.inner-->
</div>
<!--/.contents-->

<%= render "shared/footer" %>

app/views/novels/concept.html.erb
<body class="home">
<%= render "shared/header" %>
<div class="contents bg2">
<div class="inner">

	<section>
  
  <h2>コンセプト</h2>

  <div class="box1">
	<figure class="fr w30p"><%= image_tag "book.jpg" %></figure>
	<div class="fl w65p">
	<h4>当サイトの目的</h4>
	<p>当アプリの目的は「新たな小説との出会いを提供すること」です。<br>
  その切り口は、「物語の中で舞台となっている地域」としています。<br><br>
  サイト名の「noverea（ノべリア）」は、「novel × area」の造語です。</p>
	</div>
	</div>

  <div class="box1">
    <figure class="fr w30p"><%= image_tag "book2.jpg" %><%= image_tag "map.jpg" %></figure>
    <div class="fl w65p">
      <h4>当サイトの制作経緯</h4>
      <p>旅行が趣味の作者は、旅行予定地を舞台としている小説を事前に読み、その地への思い入れを深くすることで、旅行をより有意義なものにしてきました。
      しかし、ある特定の地域を舞台にした小説、それも自分の好みに合った小説を簡単に探せる場が少ないと長らく感じていました。<br><br>
    
      読書を好む方はたくさんおられます。しかし、読書愛好家100人が集まって、これまで読んだ小説を持ち寄っても、全く同じ読書歴を持つ人はいないでしょう。<br>
      世に小説は五万とあり、今現在も素晴らしい作家の皆様が新たな作品を生み出し続けているのですから。<br>
      様々な小説を読んできた読書愛好家のみなさまが、自身の好きな作品の舞台になったのはここだ！、と知識を持ち寄れば、それはとても素晴らしい情報の集約地になるのではないでしょうか。<br><br>
      
      そしてこの「小説」「舞台となった地域」に関する情報の集約地は、次なる小説との出会いを探す皆様の助けとなるでしょう。<br>
      「旅行先」に限らず、「住んでいる場所」「勤務先」「通勤通学の途中のあの場所」「友人宅」「テレビで見て素敵だと思った場所」エトセトラ。地域と人との関係には、様々な形があります。<br>
      ですのでぜひ、気になる地域や馴染みある場所、そこを舞台にした小説との出会いを、当サイトを通じて見つけていただけますと幸いです。</p>
    </div>
	</div>

  </section>

  </div>
  <!--/.inner-->
  </div>
  <!--/.contents-->
  <%= render "shared/footer" %>

app/views/novels/create.html.erb
<body class="home">
<%= render "shared/header" %>
<div class="contents">
<div class="inner">

<section>
 <h2 class="simple">投稿が完了しました</h2>
  <p>
    <strong class="color1">
    <%= link_to 'さらに小説情報を投稿する', new_novel_path %><br>
    <%= link_to 'ホームに戻る', novels_path %></strong>
  </p>


</section>
</div>
<!--/.inner-->
</div>
<!--/.contents-->

<%= render "shared/footer" %>

app/views/novels/edit.html.erb
<body class="home">
<%= render "shared/shortheader" %>
<div class="contents">
<div class="inner">

<section>
  <h2>小説情報編集</h2>
  <p>
    <strong class="color1">当該小説情報の削除を希望される場合は、お手数ですが、お問い合わせフォームよりご連絡ください。</strong><br>
  </p>
  <%= form_with model: @novel, local: true do |f| %>
    <table class="ta1">
      <tbody>
        <tr>
          <th><%= f.label :タイトル（必須） %></th>
          <td><%= f.text_field :title, placeholder: "小説のタイトル",class:"inputtype-text" %></td>
        </tr>
        <tr>
          <th><%= f.label :著者（必須） %></th>
          <td><%= f.text_field :auther, placeholder: "著者名",class:"inputtype-text" %></td>
        </tr>
        <tr>
          <th><%= f.label :作品ジャンル %></th>
          <td><%= f.collection_select(:genre_id, Genre.all, :id, :name, {})  %></td>
        </tr>
        <tr>
          <th><%= f.label :舞台となった地域 %></th>
          <td><select name="novel[area_ids][]">
                <option value="">地域を選択してください</option>
              <% Area.all.each do |area| %>
                <option value=<%= area.id %>><%= area.country %>,<%= area.prefecture %>,<%= area.city %></option>
              <% end %>
          </select>
            <% country = @novel.areas&.first&.country %>
            <% prefecture = @novel.areas&.first&.prefecture %>
            <% city = @novel.areas&.first&.city %>
          <% if country != nil %>
            登録中の地域「<%= country %>,<%= prefecture %>,<%= city %>」
          <% end %>
          </td>
        </tr>
        <tr>
          <th><%= f.label :その他地域 %></th>
          <td><%= f.text_field :another_area, placeholder: "上記プルダウンにない地域はこちらに入力",class:"inputtype-text" %></td>
        </tr>
        <tr>
          <th><%= f.label :スポット %></th>
          <td><%= f.text_field :spot, placeholder: "舞台となった施設等(例：国会議事堂、渋谷ヒカリエ、ルーブル美術館)",class:"inputtype-text" %></td>
        </tr>
        <tr>
          <th><%= f.label :小説のあらすじ %></th>
          <td><%= f.text_area :synopsis, placeholder: "あらすじ（1000字以内）" , class:'synopsis-input' %></td>
        </tr>
        <tr>
          <th><%= f.label :メディアミックス %></th>
          <td><%= f.text_field :mediamix, placeholder: "アニメ化・映画化等のメディアミックス情報",class:"inputtype-text" %></td>
        </tr>
      </tbody>
    </table>
    <%= f.submit "投稿する" ,class:'btn' %>
  <% end %>

</section>
</div>
<!--/.inner-->
</div>
<!--/.contents-->

<%= render "shared/footer" %>

app/views/novels/index.html.erb
<body class="home">
<%= render "shared/header" %>
<div class="contents">
<div class="inner">

	<section>
  <h2>簡易検索BOX</h2>
	<%= render "shared/simplesearch" %>
	</section>

</div>
<!--/.inner-->
</div>
<!--/.contents-->

<div class="contents bg2">
<div class="inner">

	<section>
	<h2>投稿作品一覧</h2>
	<p class="c">「new」最終更新日が本日の作品</p>

	<ul>
	<% count = 0 %>
	<% @novels.each do |novel| %>
		<% country = novel.areas&.first&.country %>
		<% prefecture = novel.areas&.first&.prefecture %>
		<% city = novel.areas&.first&.city %>
			<li><div class="box2">
			<% if novel.updated_at.strftime("%Y/%m/%d") == Date.today.strftime("%Y/%m/%d") %>
				<span class="date">new</span>
			<% end %>
			<h4><%= link_to novel.title, novel_path(novel.id) %></h4>
			<p>著者名: <%= novel.auther %><br>
				発売年: <%= @result[count].sales_date %><br>
				舞台:<%= country %>
						<% if prefecture != nil %>
							<%= prefecture %>
						<% end %>
						<% if city != nil %>
							<%= city %>
						<% end %><br>
						<% if country != nil %>
							<%= link_to "同じ地域が舞台となった作品一覧へ", area_path( novel.areas&.first&.id ) %>
						<% end %>
						<% if novel.another_area != nil || novel.another_area != "" %>
							<%= novel.another_area %>
						<% end %><br>
						</p>
				<div class="item">
					<div class="itemheader">商品情報【楽天BOOKS】</div>
					<div class="itembottom">
						<div class=itembottomleft>
							『<%= link_to @result[count].title, @result[count].item_url, target: :_blank, rel: "noopener noreferrer" %>』<br><br>
							<%= @result[count].item_price %>円
						</div>
						<div class=itembottomright>
							<%= link_to (image_tag(@result[count].medium_image_url)), @result[count].item_url, target: :_blank, rel: "noopener noreferrer" %>
						</div>
					</div>
					<% count += 1 %>
				</div>
	<% end %></li>
	</ul>
	</div>

	<div class="contents bg2">
		<div class="inner">
			<%= paginate @novels %>
		</div>
	</div>

	</section>

</div>
<!--/.inner-->
</div>
<!--/.contents-->

<%= render "shared/footer" %>

</body>
</html>

app/views/novels/new.html.erb
<body class="home">
<%= render "shared/shortheader" %>
<div class="contents">
<div class="inner">

<section>
  <% unless  user_signed_in? %>
    <h3>※投稿するには、ログインをしてください※
    <%= link_to "ログイン", new_user_session_path %>
    <%= link_to "新規登録", new_user_registration_path %></h3>
  <% end %>
  <h2>小説情報投稿</h2>
  <p>
    <strong class="color1">情報登録</strong><br>
    すでに投稿されている小説の情報更新は、当該小説の詳細ページから編集をお願いいたします。
  </p>

  <%= form_with model: @novel, local: true do |f| %>
    <table class="ta1">
      <tbody>
        <tr>
          <th><%= f.label :タイトル（必須） %></th>
          <td><%= f.text_field :title, placeholder: "小説のタイトル",class:"inputtype-text" %></td>
        </tr>
        <tr>
          <th><%= f.label :著者（必須） %></th>
          <td><%= f.text_field :auther, placeholder: "著者名",class:"inputtype-text" %></td>
        </tr>
        <tr>
          <th><%= f.label :作品ジャンル %></th>
          <td><%= f.collection_select(:genre_id, Genre.all, :id, :name, {})  %></td>
        </tr>
        <tr>
          <th><%= f.label :舞台となった地域 %></th>
          <td><select name="novel[area_ids][]">
                <option value="">地域を選択してください</option>
              <% Area.all.each do |area| %>
                <option value=<%= area.id %>><%= area.country %>,<%= area.prefecture %>,<%= area.city %></option>
              <% end %>
          </select></td>
        </tr>
        <tr>
          <th><%= f.label :その他地域 %></th>
          <td><%= f.text_field :another_area, placeholder: "上記プルダウンにない地域はこちらに入力",class:"inputtype-text" %></td>
        </tr>
        <tr>
          <th><%= f.label :スポット %></th>
          <td><%= f.text_field :spot, placeholder: "舞台となった施設等(例：国会議事堂、渋谷ヒカリエ、ルーブル美術館)",class:"inputtype-text" %></td>
        </tr>
        <tr>
          <th><%= f.label :小説のあらすじ %></th>
          <td><%= f.text_area :synopsis, placeholder: "あらすじ（1000字以内）" , class:'synopsis-input' %></td>
        </tr>
        <tr>
          <th><%= f.label :メディアミックス %></th>
          <td><%= f.text_field :mediamix, placeholder: "アニメ化・映画化等のメディアミックス情報",class:"inputtype-text" %></td>
        </tr>
      </tbody>
    </table>
    <% if  user_signed_in? %>
    <%= f.submit "投稿する" ,class:'btn' %>
    <% end %>
  <% end %>
  <% unless  user_signed_in? %>
  <h3>※投稿するには、ログインしてください※
  <%= link_to "ログイン", new_user_session_path %>
  <%= link_to "新規登録", new_user_registration_path %></h3>
<% end %>

</section>
</div>
<!--/.inner-->
</div>
<!--/.contents-->

<%= render "shared/footer" %>

app/views/novels/search.html.erb
<body class="home">
<%= render "shared/shortheader" %>
<div class="contents">
<div class="inner">

<section>
<h2>簡易検索BOX</h2>
<%= render "shared/simplesearch" %>
</section>

<section>
<h2>検索結果</h2>
<ul>
<% count = 0 %>
<% @novels.each do |novel| %>
  <% country = novel.areas&.first&.country %>
  <% prefecture = novel.areas&.first&.prefecture %>
  <% city = novel.areas&.first&.city %>
    <li><div class="box2">
    <% if novel.updated_at.strftime("%Y/%m/%d") == Date.today.strftime("%Y/%m/%d") %>
      <span class="date">new</span>
    <% end %>
    <h4><%= link_to novel.title, novel_path(novel.id) %></h4>
    <p>著者名: <%= novel.auther %><br>
      発売年: <%= @result[count].sales_date %><br>
      舞台:<%= country %>
          <% if prefecture != nil %>
            <%= prefecture %>
          <% end %>
          <% if city != nil %>
            <%= city %>
          <% end %><br>
          <% if country != nil %>
            <%= link_to "同じ地域が舞台となった作品一覧へ", area_path( novel.areas&.first&.id ) %>
          <% end %>
          <% if novel.another_area != nil || novel.another_area != "" %>
            <%= novel.another_area %>
          <% end %><br>
      </p>
      <div class="item">
        <div class="itemheader">商品情報【楽天BOOKS】</div>
        <div class="itembottom">
        <div class=itembottomleft>
          『<%= link_to @result[count].title, @result[count].item_url, target: :_blank, rel: "noopener noreferrer" %>』<br><br>
          <%= @result[count].item_price %>円
        </div>
        <div class=itembottomright>
          <%= link_to (image_tag(@result[count].medium_image_url)), @result[count].item_url, target: :_blank, rel: "noopener noreferrer" %>
        </div>
			</div>
      <% count += 1 %>
 <% end %></div></li>
</ul>

<div class="contents bg2">
<div class="inner">
  <%= paginate @novels %>
</div>
</div>
</section>
</div>
<!--/.inner-->
</div>
<!--/.contents-->

<%= render "shared/footer" %>

app/views/novels/show.html.erb
<body class="home">
<%= render "shared/shortheader" %>
<div class="contents">
<div class="inner">

<section>
  <h2>作品詳細</h2>

  <h3>基本情報</h3>
  <p><strong class="color1">■タイトル■</strong>
      <%= @novel.title %><br>
    <strong class="color1">■著作者■</strong>
      <%= @novel.auther %><br>
    <strong class="color1">■発売年■</strong>
      <%=  @item.sales_date %><br>
    <strong class="color1">■作品ジャンル■</strong>
      <%= @novel.genre.name %><br>
    <strong class="color1">■物語の舞台となった地域■</strong>
      <% country = @novel.areas&.first&.country %>
      <% prefecture = @novel.areas&.first&.prefecture %>
      <% city = @novel.areas&.first&.city %>
      <% if country != nil %>
        <%= country %>,
      <% end %>
      <% if prefecture != nil %>
        <%= prefecture %>,
      <% end %>
      <% if city != nil %>
        <%= city %>
      <% end %>
      <% if country != nil %>
      <%= link_to "同じ地域が舞台となった作品一覧へ", area_path( @novel.areas&.first&.id ) %>
      <% end %>
      <% if @novel.another_area != nil || @novel.another_area != "" %>
        <%= @novel.another_area %>
      <% end %><br>
    <strong class="color1">■スポット■</strong>
      <%= @novel.spot %><br>
    <strong class="color1">■メディアミックス■</strong>
      <%= @novel.mediamix %><br>
  </p>
  <% if  user_signed_in? %>
    <p class="btn1 a"><%= link_to "基本情報を編集する", edit_novel_path(@novel.id) %></p>
  <% else %>
    <p> ※基本情報の編集をする場合、ログインをしてください。
    <%= link_to "ログイン", new_user_session_path %>
    <%= link_to "新規登録", new_user_registration_path %>
    </p>
  <% end %>


  <h3>商品情報</h3>
  <div class="box1 left leftstyle">
    <h4><%= link_to @item.title, @item.item_url, target: :_blank, rel: "noopener noreferrer" %></h4><br>
    <div class="box1bottom">
      <div class="box1left">
        <%= link_to image_tag(@item.large_image_url), @item.item_url, target: :_blank, rel: "noopener noreferrer" %>
      </div>
      <div class="box1right">
        発売日情報：<%= @item.sales_date %><br>
        <%= @item.item_caption %>
      </div>
    </div>
  </div>
  <% unless @dvditem.nil? %>
    <div class="box1 left leftstyle">
      <h4><%= link_to @dvditem.title, @dvditem.item_url, target: :_blank, rel: "noopener noreferrer" %></h4><br>
      <div class="box1bottom">
        <div class="box1left">
          <%= link_to image_tag(@dvditem.large_image_url), @dvditem.item_url, target: :_blank, rel: "noopener noreferrer" %>
        </div>
        <div class="box1right">
          発売日情報：<%= @dvditem.sales_date %><br>
          <%= @dvditem.artist_name %><br>
          <%= @dvditem.item_caption %>
        </div>
      </div>
    </div>
  <% end %>

  <h3>コメント</h3>



</section>
</div>
<!--/.inner-->
</div>
<!--/.contents-->

<%= render "shared/footer" %>