config/routes.rb
Rails.application.routes.draw do  
  namespace :admins do
    get 'toppages/index'
  end
  devise_for :admins, controllers: {
    sessions:      'admins/sessions',
    passwords:     'admins/passwords',
    #registrations: 'admins/registrations'
  }
  devise_scope :admin do
    get '/admins/sign_out' => 'admins/sessions#destroy'
  end
  devise_for :users, controllers: {
    sessions:      'users/sessions',
    passwords:     'users/passwords',
    registrations: 'users/registrations'
  }
  root to:"novels#index"
  get 'novels/complete'
  get 'novels/concept'
  resources :novels, only: [:index, :new, :create, :show, :edit, :update] do
    collection do
      get 'search'
      get 'search_area'
    end
  end
  resources :areas, only: [:new, :create, :show] do
    collection do
      get 'search'
    end
  end
end

app/models/area.rb
class Area < ApplicationRecord
  has_many :novel_areas
  has_many :novels, through: :novel_areas

  validates :country, presence: true

end

app/models/form/area.rb
class Form::Area < Area
  REGISTRABLE_ATTRIBUTES = %i(country prefecture city)
  attr_accessor :country
end

app/controllers/areas_controller.rb
class AreasController < ApplicationController
  before_action :authenticate_admin!, only:[ :new, :create ]

  def new
    @form = Form::AreaCollection.new
  end

  def create
    @area = Form::AreaCollection.new(area_collection_params)
    if @area.save
      redirect_to :new
    else
      render :new
    end
  end

  def show
    @area = Area.find(params[:id])
    #if @area.city == nil
    #  @same_country_id = Area.where(country:@area.country, prefecture:nil, city:nil).ids
    #elsif @area.city != nil
    #  @same_country_id = Area.where(country:@area.country, prefecture:nil, city:nil).ids
    #  @same_country_pre_id = Area.where(country:@area.country, prefecture:@area.prefecture, city:nil).ids
    #end
    @novels = @area.novels
    @result = []

    @novels.each do |novel|
      title = novel.title
      auther = novel.auther
      search_rakuten_api(title, auther)
      @result << @item
    end
  end

  private

  def area_collection_params
    params
      .require(:form_area_collection)
      .permit(areas_attributes: Form::Area::REGISTRABLE_ATTRIBUTES)
  end

  def search_rakuten_api(title, auther)
    RakutenWebService.configure do |c|
      c.application_id = ENV["RAKUTEN_APP_KEY_ID"]
      c.affiliate_id = ENV["RAKUTEN_AFFILIATE_KEY_ID"]
    end
    items = RakutenWebService::Books::Book.search(title: title, auther: auther)
    items.first(1).each do |item|
      @item = item
    end
  end

  def search_rakuten_api_dvd(title)
    RakutenWebService.configure do |c|
      c.application_id = ENV["RAKUTEN_APP_KEY_ID"]
      c.affiliate_id = ENV["RAKUTEN_AFFILIATE_KEY_ID"]
    end
    items = RakutenWebService::Books::DVD.search(title: title)
    items.first(1).each do |item|
      @dvditem = item
    end
  end
end

app/helpers/areas_helper.rb
module AreasHelper
end

app/views/areas/new.html.erb
<div class="contents">
<div class="inner">


<section>
<h2>地域情報追加</h2>

  <%= form_with(model:@form, url: areas_path, method: :post) do |f| %>
  <table class="ta1">
    <tbody>
      <tr>
        <th>国</th>
        <th>都道府県/州</th>
        <th>市区町村</th>
      </tr>
    </thead>
    <tbody>
      <%= f.fields_for :areas do |i| %>
        <tr>
          <td>
          <%= i.text_field :country %>
          </td>
          <td>
          <%= i.text_field :prefecture %>
          </td>
          <td>
          <%= i.text_field :city %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <%= f.submit '一括登録', class: 'btn' %>
<% end %>

</section>
<section>
<%= link_to "管理者ログアウト", destroy_admin_session_path, mothod: :delete, class:"another-btn" %>
<%= link_to "管理者トップページへ", admins_toppages_index_path, class:"another-btn" %><br><br>
</section>
</div>
<!--/.inner-->
</div>
<!--/.contents-->

<%= render "shared/footer" %>

app/views/areas/search.html.erb
<body class="home">
<%= render "shared/shortheader" %>
<div class="contents">
<div class="inner">

<section>
<h2>簡易検索BOX</h2>
<%= render "shared/simplesearch" %>
</section>

<section>
<h2>検索結果</h2>
<ul>
<% count = 0 %>
<% @novels.each do |novel| %>
  <% novel.each do |novel| %>
    <% country = novel.areas&.first&.country %>
    <% prefecture = novel.areas&.first&.prefecture %>
    <% city = novel.areas&.first&.city %>
    <li><div class="box2">
    <h4><%= link_to novel.title,  novel_path(novel.id) %></h4>
    <p>著者名: <%= novel.auther %><br>
        発売年: <br>
        舞台:<%= country %>
            <% if prefecture != nil %>
              <%= prefecture %>
            <% end %>
            <% if city != nil %>
              <%= city %>
            <% end %>
            <% if novel.another_area != nil || novel.another_area != "" %>
              <%= novel.another_area %>
            <% end %><br>
            </p>
          <% count += 1 %>
        </div>
    <% end %>
<% end %></li>
</ul>


</section>
</div>
<!--/.inner-->
</div>
<!--/.contents-->

<%= render "shared/footer" %>

app/views/areas/show.html.erb
<body class="home">
<%= render "shared/shortheader" %>
<div class="contents">
<div class="inner">

<section>
  <h2>「<%= @area.country %><%= @area.prefecture %><%= @area.city %>」 が舞台の作品一覧</h2>

    <% if @area.prefecture == nil %>
    <% elsif @area.city == nil %>
    <p class="btn1 a"><%= link_to "#{@area.country}が舞台の作品一覧へ", '#' %></p>
    <% elsif @area.city != nil %>
      <p class="btn1 a"><%= link_to "#{@area.country}が舞台の作品一覧へ", '#' %></p>
      <p class="btn1 a"><%= link_to "#{@area.country},#{@area.prefecture}が舞台の作品一覧へ", '#' %></p>
    <% end %> 
     <ul>
  <% count = 0 %>
  <% @novels.each do |novel| %>
    <% country = novel.areas&.first&.country %>
		<% prefecture = novel.areas&.first&.prefecture %>
		<% city = novel.areas&.first&.city %>
    <li><div class="box2">
    <h4><%= link_to novel.title,  novel_path(novel.id) %></h4>
    <p>著者名: <%= novel.auther %><br>
				発売年: <%= @result[count].sales_date %><br>
				舞台:<%= country %>
						<% if prefecture != nil %>
							<%= prefecture %>
						<% end %>
						<% if city != nil %>
							<%= city %>
						<% end %>
						<% if novel.another_area != nil || novel.another_area != "" %>
							<%= novel.another_area %>
						<% end %><br>
						</p>
				<div class="item">
					<div class="itemheader">商品情報【楽天BOOKS】</div>
					<div class="itembottom">
						<div class=itembottomleft>
							『<%= link_to @result[count].title, @result[count].item_url, target: :_blank, rel: "noopener noreferrer" %>』<br><br>
							<%= @result[count].item_price %>円
						</div>
						<div class=itembottomright>
							<%= link_to (image_tag(@result[count].medium_image_url)), @result[count].item_url, target: :_blank, rel: "noopener noreferrer" %>
						</div>
					</div>
					<% count += 1 %>
				</div>
  <% end %></li>
  </ul>

  <h3>コメント</h3>



  </section>
  </div>
  <!--/.inner-->
  </div>
  <!--/.contents-->
  
  <%= render "shared/footer" %>